### ISSUE TITLE
Cannot push using SSH

### ISSUE THREAD

**Issue by ghost** [David-Wolgemuth/MEAN_December_Cohort#1]
I have to login every-time I want to push files to the repository. Please allow us to add or collaborate with us  in adding our SSH keys so this won't have to happen.

**Comment by david-wolgemuth** [comment]
Hey Dan, I think you may have cloned down using HTTPS instead of SSH.  Easy fix is for you to re-clone, but specifying SSH.  Let me know if this doesn't work for you.

https://help.github.com/articles/why-is-git-always-asking-for-my-password/
